### PR TITLE
Fix HTML attribute warnings in Description component fixes #47

### LINKED ISSUE #47: Warning: Received `false` for a non-boolean attribute `loading`.
Console warning appears in the project when adding ReactTinyLink:
image

Use case: create clean react project (npx create-react-app my-app), insert in App.js:
<ReactTinyLink
          cardSize="small"
          showGraphic
          maxLine={2}
          minLine={1}
          url="https://reactjs.org"
          />
image

### PR DESCRIPTION
**Pull request by aviskarkc10**
This PR addresses the issues of various HTML attributes error like `loading`, `minLine`, `maxLine` and so on showing up on console. I used this as a reference to fix this issue: 
https://styled-components.com/docs/faqs#why-am-i-getting-html-attribute-warnings

### CODE REVIEW

File: src/components/Description.tsx [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+export const Description = styled(UnstyledDescription)<{ loading: boolean }>`
+  &&& {
+    text-align: inherit;
+    font-weight: inherit;
+    font-family: inherit;
+    color: inherit;
+    margin: 0;
+    ${({ loading }) => loading && loadingStyle}
+  }
+`;
```
Comment (winhtaikaung) [inline src/components/Description.tsx:44]: Can we remove `;`?

Comment (aviskarkc10) [reply src/components/Description.tsx]: fixed

**Comment by winhtaikaung** [comment]
@all-contributors please add @aviskarkc10  for bug and code
